columns:
  speed:
    time_series
  cadence:
    time_series
  power:
    time_series
  torque:
    time_series
  longitude:
  latitude:
  altitude:
  heart-rate:
    time_series
  w/kg:
    time_series
  slope:
    time_series
  distance:
time_series:
  raw:
  1s:
  5s:
  30s:
  1min:
  5min:
  20min:
fit_map:
  enhanced_speed: speed
  cadence: cadence
  power: power
  position_long: longitude
  position_lat: latitude
  altitude: altitude
  heart_rate: heart-rate
  distance: distance
  timestamp: time